### ISSUE TITLE
Consider adding collaborators

### ISSUE THREAD

**Issue by AdrienTorris** [AdrienTorris/awesome-blazor#130]
I consider adding some collaborators. I want this repo very community-driven so it's a non-sense that I am the only one who can merge the submitted PRs.  Moreover, it will allow this repo to be always active and avoid it to be frozen when I am in holidays, like at the end of May this year.

**Comment by stsrki** [comment]
I might be interested to be more involved.

**Comment by chrissainty** [comment]
I’d be interested

**Comment by SamProf** [comment]
I am also in

**Comment by ctrl-alt-d** [comment]
I'm also interested in collaborating.

**Comment by AdrienTorris** [comment]
Hi everyone.

I was not expected so much interest, thank's. I'm sorry but I need a few days to decide how to choose the good profiles, or maybe everyone? It's an open question. Let me think about that. And don't hesitate to tell what you think here.

Thank you for your interest and for all the stuff you are doing for Blazor.

**Comment by SamProf** [comment]
@AdrienTorris I think you should understand for yourself what you expect from collaborators.
For my opinion there are few goals to have other collaborators

- Manage PRs
- Search new content for awsome-blazor
- Changing existing content to make it more nice. For example few time ago we merge all Components and Librarries groups into one, because they have same content. But for my opinion they should be separated by library-type, something like Components, Js Interop,,  etc

So, what you expect from collaborators?

**Comment by stsrki** [comment]
I agree with @SamProf. Maybe there is not that much work to do here but regardless, it could still take some time for all of us. Also if there would be more of collaborators they should communicate more and agree of the direction and structure of the _awesome_ list.

The categories definitely need some restructuring, and I also think there are too many _simple_ applications that the people are posting. Although they are still worthy for the beginners, they should maybe be in their own category.

Maybe it's the best to strive for quality instead of quantity when building the list.

**Comment by ctrl-alt-d** [comment]
Blazor is moving fast and some links become deprecated. With more hands may be easiest to manage content, be kind to people and keep repo up to date. As a PR collaborator, I appreciate a quick response from maintainers. Quick response don't mean to merge PR, just to keep collaborators informed of the "merge" or "reject" process and be grateful for the contributions. On the other hand I am reading good ideas in this thread from @SamProf  and @stsrki.

**Comment by AdrienTorris** [comment]
I agree with you, we definitely have to restructure the page and prefer quality over quantity (which is not easy to do, it's difficult to tell to someone that his sample or library is not enough interesting to be mentioned on Awesome Blazor).

I just published a [post](https://adrientorris.github.io/aspnetcore/blazor/which-plans-for-awesome-blazor) to explain the reasons why I want to add some collaborators and to be honest I didn't anticipate that several people would be interested.

I saw that Chris Sainty was interested, if it's still the case I'll add him first, I think he's absolutely perfect for this. He's a maintainer of some libraries, he has a great blog and writes a lot about Blazor, he does talks, in short, he's a public figure around Blazor. I do not tell that all the future collaborators will have to be public figures (I will be the first troubled doing that ^^) and you all are really relevant candidates (I mean it, I visited all your profiles the last two days), but I have to start with someone.
Now the questions are "How many contributors?" and "How organize the collaboration to make this repository a relevant resource to any Blazor developer?".

**Comment by SamProf** [comment]
@AdrienTorris I think think that it should be completly your decision.

I think that "awsome" should be open for everyone and any component library can be presented here. but for example you can have group with most starred projects. (or most popular).

Or maybe just in list show count of starts in list.

**Comment by mauriliofilho** [comment]
I'm Interested to, so pleasure contribute to this repo

**Comment by stsrki** [comment]
@AdrienTorris I agree that it's not easy to say someone their code is not that good. Just to be clear, I'm here talking about sample or test applications and not about tools or libraries that people are posting. Some control will have to be if this is going to be an _awesome-list_ and not an _all-list_. Maybe there could be a list of missing _real-world_ examples that people could vote for. And someone can took it and create it.

PS. Chris Sainty is an excellent choice.
